# Generated by Django 4.0.2 on 2022-03-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zafi_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race_uid',
            field=models.CharField(default='', max_length=32, verbose_name='Race UID'),
        ),
    ]
