# Generated by Django 4.0.2 on 2022-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zafi_api', '0003_character_character_money_character_character_xp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_money_per_sec', models.IntegerField(default=0, verbose_name='Add money per second:')),
                ('add_work_per_sec', models.IntegerField(default=0, verbose_name='Add work per second:')),
                ('add_money_per_click', models.IntegerField(default=0, verbose_name='Add money per click:')),
                ('add_work_per_click', models.IntegerField(default=0, verbose_name='Add work per click:')),
                ('office_upgrade_timer', models.IntegerField(default=0, verbose_name='Timer:')),
                ('office_upgrade_name', models.CharField(max_length=32, verbose_name='Upgrade name:')),
            ],
        ),
    ]
