# Generated by Django 4.0.2 on 2022-06-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zafi_api', '0004_officeupgrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeupgrade',
            old_name='add_work_per_click',
            new_name='do_work_per_click',
        ),
        migrations.RenameField(
            model_name='officeupgrade',
            old_name='add_work_per_sec',
            new_name='do_work_per_sec',
        ),
    ]
