# Generated by Django 4.0.2 on 2022-06-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zafi_api', '0005_rename_add_work_per_click_officeupgrade_do_work_per_click_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeupgrade',
            name='do_work_per_click',
            field=models.IntegerField(default=0, verbose_name='Do work per click:'),
        ),
        migrations.AlterField(
            model_name='officeupgrade',
            name='do_work_per_sec',
            field=models.IntegerField(default=0, verbose_name='Do work per second:'),
        ),
    ]
