# Generated by Django 4.0.2 on 2022-06-23 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('zafi_api', '0007_character_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileOfficeUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zafi_api.officeupgrade')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zafi_api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='upgrades',
            field=models.ManyToManyField(through='zafi_api.UserProfileOfficeUpgrade', to='zafi_api.OfficeUpgrade'),
        ),
    ]
